### ISSUE TITLE
Maximum result length is inflexible

### ISSUE THREAD

**Issue by ambihelical** [abo-abo/define-word#10]
Please consider making the maximum length of results configurable, instead of a constant 10.  It would be great if the length could be configurable as either some fraction of the frame height at invocation or some number of lines.

**Comment by abo-abo** [comment]
Does `define-word-limit` not work?

**Comment by ambihelical** [comment]
Isn't it defconst?  Setting it via setq didn't have any effect, went back to 10.  Could be something I don't know about, relatively noob at elisp.

**Comment by abo-abo** [comment]
I'm able to change `defconst` values with `setq`. The const-ness isn't enforced anywhere. Anyway, I'll change it to `defvar` because it makes more sense.
