### ISSUE TITLE
Fails on resolving plural words

### ISSUE THREAD

**Issue by jonsnader** [abo-abo/define-word#13]
When looking up the singular form of a plural word that doesn't have a matching verb form, define-word will fail with "define-word: Wrong type argument: stringp, ("Fetching singular...")" You can see this behavior by looking up the word "pears", which will fail while the word "pear" resolves correctly. This is caused by the apparently spurious `'("Fetching singular...")` at line 135. When I delete the `'("Fetching singular...")`, define-word handles the plural forms correctly.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by jonsnader** [comment]
It's working now. Thanks.
