### ISSUE TITLE
Using other thesaurus services, e.g. for german

### ISSUE THREAD

**Issue by MartinBuchmann** [abo-abo/define-word#16]
Thanks a lot for this nice package. It works nicely with english words using wordnik. But I could not figure out how to use it for a german thesaurus like [Openthesaurus](https://www.openthesaurus.de). How do I have to customize define-word-services?

I tried to add a new service using the url `https://www.openthesaurus.de/synonyme/%s` but it gives me only the message `0 definitions found`.

**Comment by abo-abo** [comment]
> Thanks a lot for this nice package.

You're welcome.

> It works nicely with english words using wordnik. But I could not figure out how to use it for a german thesaurus like Openthesaurus. How do I have to customize define-word-services?

Wordnik works by fetching the raw HTML and parsing it. So to add a different service you have to define your own parser.

I'll add some code for you. I tested it a bit and it seems to work. Improvements welcome.

**Comment by MartinBuchmann** [comment]
That's pretty cool! It works but german umlauts (ä, ö, ü etc.) are displayed as html-encode(?) versions, i.e. &auml; I did not find an already implemented function which exchanges these characters but will look for it again if I have more time.

**Comment by MartinBuchmann** [comment]
I found the time to have a look at the issue with the german umlauts, finally.

I came up with something like this:

```
(defun de-escape (string)
  "Replaces html encoded umlauts with their proper character."
  (let ((replacements '(("&Auml;" "Ä")
                        ("&auml;" "ä")
                        ("&Eacute;" "É")
                        ("&eacute;" "é")
                        ("&Ouml;" "Ö")
                        ("&ouml;" "ö")
                        ("&Uuml;" "Ü")
                        ("&uuml;" "ü")
                        ("&szlig;" "ß")))
        (case-fold-search nil))
    (with-temp-buffer
      (insert string)
      (dolist (replacement replacements)
        (cl-destructuring-bind (old new) replacement
          (goto-char (point-min))
          (while (search-forward old nil t)
            (replace-match new))))
      (buffer-string))))

(defun define-word--parse-openthesaurus ()
  "Parse output from openthesaurus site and return formatted list"
  (save-match-data
    (let (results part beg)
      (goto-char (point-min))
      (nxml-mode)
      (while (re-search-forward "<sup>" nil t)
        (goto-char (match-beginning 0))
        (setq beg (point))
        (nxml-forward-element)
        (delete-region beg (point)))
      (goto-char (point-min))
      (while (re-search-forward
              "<span class='wiktionaryItem'> [0-9]+.</span>\\([^<]+\\)<" nil t)
        (setq part (match-string 1))
        (backward-char)
        (push (string-trim part) results))
      (setq results (nreverse results))
      (if (= 0 (length results))
          (message "0 definitions found")
        (when (> (length results) define-word-limit)
          (setq results (cl-subseq results 0 define-word-limit)))
        (mapconcat #'de-escape results "\n")))))
```

As I am very un-experienced with emacs lisp, could you please check this and integrate this in the next commit if possible. It works fine for on my system.

Thanks a lot!

**Comment by poulpoulsen** [comment]
hello,
thanks for the fix, but unfortunately here it doesnt work. Some  html-encode are still visible.
If i paste the result , its ok.
Strange
Regards
Poul

**Comment by MartinBuchmann** [comment]
@poulpoulsen I noticed recently that something changed, too. I know very little about character encoding etc. but its seems to me that something has changed with openthesaurus' output format.

I added 

```
("\303\244" "ä")
("\342\200\236" "„")
("\342\200\234" "“") 
```

to the list of `replacements` in `de-escape` and it was okay for the word I was looking for. I hadn't the time to complete the list of possible replacements further but if you could send me the characters which are wrong in our case we could update it incrementally.
