### ISSUE TITLE
Clever definitions by ignoring plural/tense ...

### ISSUE THREAD

**Issue by easbarba** [abo-abo/define-word#17]
Hey, wordnik returns some "dumb" definitions as:

**pangs** >  _Plural form of pang..._

I think that most users wants

 **pang** definition: _A sudden sharp spasm of pain. See Synonyms at pain..._ 

So I propose a variable that ignores plural and tense definition by trimming words as **pangs** to **pang**, **loathed** to **loath**!

I know some issues will arise as words that ends with s (malicious) but I still think there might be a solution to it...

What yall think about it? 

Thanks!

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by easbarba** [comment]
Wow, AMAZING!
