### ISSUE TITLE
Not enough arguments for format string Error

### ISSUE THREAD

**Issue by leolcling** [abo-abo/define-word#23]
Hi. For some words, `define-word`  would return "Not enough arguments for format string"  error. For other words, the definition is not nicely parsed. 

`M-x define-word` `road` `RET`

_Error:_

> Debugger entered--Lisp error: (error "Not enough arguments for format string")
>   message(#("noun <i></i>  An open, generally public way for the passage of vehicles, people, and animals.\nnoun <i></i>  The surface of a road; a roadbed.\nnoun <i></i>  A course or path.\nnoun <i></i>  A railroad.\nnoun <i>Nautical</i>  A roadstead.\nidiom <i></i>  (<em>down the road</em>)  In the future; at a later date.\nidiom <i></i>  (<em>on the road</em>)  On tour, as a theatrical company.\nidiom <i></i>  (<em>on the road</em>)  Traveling, especially as a salesperson.\nidiom <i></i>  (<em>on the road</em>)  Wandering, as a vagabond.\nnoun <i></i>  The tour or route of a theatrical company. See <internalXref urlencoded=\"on%20the%20road\">on the road</internalXref>." 0 5 (face define-word-face-1) 5 93 (face define-word-face-2) 94 99 (face define-word-face-1) 99 141 (face define-word-face-2) 142 147 (face define-word-face-1) 147 173 (face define-word-face-2) 174 179 (face define-word-face-1) 179 199 (face define-word-face-2) 200 205 (face define-word-face-1) 205 234 (face define-word-face-2) 235 241 (face define-word-face-1) 241 307 (face define-word-face-2) 308 314 (face define-word-face-1) 314 380 (face define-word-face-2) 381 387 (face define-word-face-1) 387 459 (face define-word-face-2) 460 466 (face define-word-face-1) 466 524 (face define-word-face-2) 525 530 (face define-word-face-1) 530 656 (face define-word-face-2)))
>   funcall(message #("noun <i></i>  An open, generally public way for the passage of vehicles, people, and animals.\nnoun <i></i>  The surface of a road; a roadbed.\nnoun <i></i>  A course or path.\nnoun <i></i>  A railroad.\nnoun <i>Nautical</i>  A roadstead.\nidiom <i></i>  (<em>down the road</em>)  In the future; at a later date.\nidiom <i></i>  (<em>on the road</em>)  On tour, as a theatrical company.\nidiom <i></i>  (<em>on the road</em>)  Traveling, especially as a salesperson.\nidiom <i></i>  (<em>on the road</em>)  Wandering, as a vagabond.\nnoun <i></i>  The tour or route of a theatrical company. See <internalXref urlencoded=\"on%20the%20road\">on the road</internalXref>." 0 5 (face define-word-face-1) 5 93 (face define-word-face-2) 94 99 (face define-word-face-1) 99 141 (face define-word-face-2) 142 147 (face define-word-face-1) 147 173 (face define-word-face-2) 174 179 (face define-word-face-1) 179 199 (face define-word-face-2) 200 205 (face define-word-face-1) 205 234 (face define-word-face-2) 235 241 (face define-word-face-1) 241 307 (face define-word-face-2) 308 314 (face define-word-face-1) 314 380 (face define-word-face-2) 381 387 (face define-word-face-1) 387 459 (face define-word-face-2) 460 466 (face define-word-face-1) 466 524 (face define-word-face-2) 525 530 (face define-word-face-1) 530 656 (face define-word-face-2)))
>   (let* ((service (or service (if choose-service (intern (completing-read "Service: " define-word-services)) define-word-default-service))) (results (define-word--to-string word service))) (funcall (define-word-displayfn service) (cond ((not results) "0 definitions found") ((define-word--expand "Plural form of \\(.*\\)\\.$" results service)) ((define-word--expand "Past participle of \\(.*\\)\\.$" results service)) ((define-word--expand "Present participle of \\(.*\\)\\.$" results service)) (t results))))
>   define-word("road" nil nil)
>   funcall-interactively(define-word "road" nil nil)
>   call-interactively(define-word nil nil)
>   command-execute(define-word)
> 

`M-x define-word` `test` `RET` 
<img width="928" alt="define_word" src="https://user-images.githubusercontent.com/20397720/56451493-90dd2b00-635e-11e9-8259-a5f99ccece00.png">

I am on Arch Linux with emacs 26.2. Version: define-word-20190128.1559. Thanks!

**Comment by averter** [comment]
Hi,

I am experiencing the same issue. I think it must be a python-related issue. I am on Linux Mint 19.1 Cinnamon using emacs 25.2.2.

**Comment by abo-abo** [comment]
> M-x define-word road RET

Works fine for me.

> M-x define-word test RET

The italics were fixed recently as well.

**Comment by leolcling** [comment]
Confirm that `M-x define-word road RET` and `M-x define-word test RET` work now with the new version. 

@abo-abo Do you mind testing `M-x define-word the` and `M-x define-word hello` for me? I got the "Not enough arguments for format string" for the first case and this for the latter. 

> Debugger entered--Lisp error: (error "Not enough arguments for format string")
>   message(#("definite article.   Used before singular or plural nouns and noun phrases that denote particular, specified persons or things.\ndefinite article.   Used before a noun, and generally stressed, to emphasize one of a group or type as the most outstanding or prominent.\ndefinite article.   Used to indicate uniqueness.\ndefinite article.   Used before nouns that designate natural phenomena or points of the compass.\ndefinite article.   Used as the equivalent of a possessive adjective before names of some parts of the body.\ndefinite article.   Used before a noun specifying a field of endeavor.\ndefinite article.   Used before a proper name, as of a monument or ship.\ndefinite article.   Used before the plural form of a numeral denoting a specific decade of a century or of a lifespan.\ndefinite article.   Used before a singular noun indicating that the noun is generic.\ndefinite article.   Used before an adjective extending it to signify a class and giving it the function of a noun.\na numeral denoting a specific decade of a century or of a lifespan:\n  adj. Not found, especially of a\n  \011\011\011\011\011\011\011\011\011\011<a href='/words/web%20page'>web page</a>\n  \011\011\011\011\011\011\011\011\011\011on the\n  \011\011\011\011\011\011\011\011\011\011<a href='/words/internet'>internet</a>.\n  \011\011\011\011\011</ul>\n  \011\011\011\011</div>\011\n  \011\011\011\011<div class=\"word-module module-etymologies\">\n  \011\011\011\011\011<h2>Etymologies</h2>\n  \011\011\011\011\011<div class=\"guts\">\n  \011\011\011\011\011\011<div class=\"sub-module\">\n  \011\011\011\011\011\011\011From the HTTP error status code 404, meaning Not Found, returned by a web server responding to a request for a non-existent URL. (Wiktionary)\n  \011\011\011\011\011\011</div>\n  \011\011\011\011\011</div>\n  \011\011\011\011</div>\n  \n  \011\011\011</div>\n  \011\011</div>\n  \011\011<div id='module-2columnRight'>\n  \011\011\011\011<div class='examples-module'>\n  \011\011\011\011\011<div class='word-module module-examples' data-name=\"examples\">\n  \011\011\011\011\011\011<h2>Page Not Found</h2>\n  \011\011\011\011\011\011<div class=\"guts\">\n  \011\011\011\011\011\011\011<ul class=\"examples\">\n  \011\011\011\011\011\011\011\011<li class=\"exampleItem\">\n  \011\011\011\011\011\011\011\011\011<p class=\"text\">You've found our 404 page. This is the page we show you when we can't show you the page you wanted, either because it doesn't exist, or because of some other error. Instead, we're showing you the definition and the etymology for the word '404', and some D\303\274rer rhinos (because we like them).</p>\n  \011\011\011\011\011\011\011\011\011<p class=\"source\"><a href=\"mailto:feedback@wordnik.com\" target=\"_blank\">Think this is a mistake? Click here to report this error.</a></p>\n  \011\011\011\011\011\011\011\011" 0 18 (face define-word-face-1) 18 126 (face define-word-face-2) 127 145 (face define-word-face-1) 145 264 (face define-word-face-2) 265 283 (face define-word-face-1) 283 313 (face define-word-face-2) 314 332 (face define-word-face-1) 332 410 (face define-word-face-2) 411 429 (face define-word-face-1) 429 519 (face define-word-face-2) 520 538 (face define-word-face-1) 538 590 (face define-word-face-2) 591 609 (face define-word-face-1) 609 663 (face define-word-face-2) 664 682 (face define-word-face-1) 682 782 (face define-word-face-2) 783 801 (face define-word-face-1) 801 867 (face define-word-face-2) 868 886 (face define-word-face-1) 886 982 (face define-word-face-2) 983 1049 (face define-word-face-2) 1053 1058 (face define-word-face-1) 1058 1084 (face define-word-face-2) 1087 1137 (face define-word-face-2) 1140 1156 (face define-word-face-2) 1159 1208 (face define-word-face-2) 1211 1221 (face define-word-face-2) 1224 1235 (face define-word-face-2) 1238 1286 (face define-word-face-2) 1289 1314 (face define-word-face-2) 1317 1340 (face define-word-face-2) 1343 1373 (face define-word-face-2) 1376 1392 (face define-word-face-2) 1392 1396 (face italic) 1396 1524 (face define-word-face-2) 1527 1539 (face define-word-face-2) 1542 1553 (face define-word-face-2) 1556 1566 (face define-word-face-2) 1572 1581 (face define-word-face-2) 1584 1592 (face define-word-face-2) 1595 1627 (face define-word-
face-2) 1630 1663 (face define-word-face-2) 1666 1733 (face define-word-face-2) 1736 1765 (face define-word-face-2) 1768 1792 (face define-word-face-2) 1795 1823 (face define-word-face-2) 1826 1858 (face define-word-face-2) 1861 2181 (face define-word-face-2) 2184 2330 (face define-word-face-2) 2333 2341 (face define-word-face-2)))
>   define-word("the" nil nil)
>   funcall-interactively(define-word "the" nil nil)
>   call-interactively(define-word nil nil)
>   command-execute(define-word)

<img width="1273" alt="Screenshot 2019-05-06 at 11 14 11 PM" src="https://user-images.githubusercontent.com/20397720/57235168-e3079700-7054-11e9-9a83-2d6446f2bd68.png">

**Comment by abo-abo** [comment]
> M-x define-word the

This one was indeed broken for me. Should be fixed now. Please test.

**Comment by leolcling** [comment]
Yes it fixed the "the"
