### ISSUE TITLE
german umlauts not displayed properly (openthesaurus)

### ISSUE THREAD

**Issue by Dapuva76** [abo-abo/define-word#25]
When using openthesaurus and getting an explanation with an umlaut, emacs display it like

> m\303\244nnlicher Vorname

I'm guessing it's something to do with encoding, not sure if I have to specify that somewhere

**Comment by abo-abo** [comment]
Please add a reproduction scenario.

**Comment by Dapuva76** [comment]
I wrote a text that included the word "Peter" or "Hans", put the cursor on the word and executed define-word-at-point, with openthesaurus being the default. The file is encoded in utf-8. I'm using the latest version of define-word off melpa. Emacs version is 26.2 on Win 10 64 bit.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by Dapuva76** [comment]
I've replaced the melpa copy of define-word with the updated one from github. Now I get

> progn: Symbol’s function definition is void: url-http--insert-file-helper

when I try to define-word-at-point with the above-mentioned settings.

**Comment by abo-abo** [comment]
Thanks, please test again.

**Comment by Dapuva76** [comment]
Perfekt. Thanks a lot & vielen Dank.
