### ISSUE TITLE
Auto-fetch singular forms

### ISSUE THREAD

**Issue by vermiculus** [abo-abo/define-word#3]
Try `define-word-at-point` on something like `organizations`. It will just say `Plural form of organization`. It would be nice if the package could recognize this response and fetch the definition for `organization` and display it as well.

The behavior I'm imagining is similar to looking up 'protected' macros with `texdef`, e.g.

```
$ texdef -t latex LaTeX

\LaTeX:
macro:->\protect \LaTeX  


\LaTeX :
\long macro:->L\kern -.36em{\sbox \z@ T\vbox to\ht \z@ {\hbox {\check@mathfonts \fontsize \sf@size \z@ \math@fontsfalse \selectfont A}\vss }}\kern -.15em\TeX 
```

**Comment by abo-abo** [comment]
Thanks.

**Comment by vermiculus** [comment]
Nope, that won't work – there are tons of words that naturally end in S. You've _got_ to parse the output.
- plus
- lens
- bus
- politics
- diabetes
- measles
- rabies
- _etc._

**Comment by abo-abo** [comment]
Oops. I cannot into English sometimes. Please check again.

**Comment by vermiculus** [comment]
oxen, boxes, …

http://english-zone.com/spelling/plurals.html

I would just nix `maybe-plural`.

**Comment by abo-abo** [comment]
> nix

Had to `define-word` that. Useful as ever.
