### ISSUE TITLE
getting error in process filter 

### ISSUE THREAD

**Issue by hisnawi** [abo-abo/define-word#8]
This is my setup:

```
  ;; Dictionary
  (use-package define-word
    :ensure t
    :bind (
           ("M-#"   . define-word-at-point)
           ("C-M-#" . define-word)
           )
    )

```

But When doing M-# I get this error:

`error in process filter: "http://wordnik.com/words/interrupts" bad request`

**Comment by abo-abo** [comment]
Works fine for me. Maybe you found a time when the server was down. Try again.

**Comment by hisnawi** [comment]
Agreed. Works now.
